sudo: required

addons:
  apt:
    update: true
  chrome:
    stable

language: python

python:
  - "3.7"

services:
  - postgresql

before_install:
  - sudo apt install -y poppler-utils
  - sudo apt install python3-psycopg2
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &

install:
  - pip install psycopg2-binary
  - pip install -r requirements.txt
  - pip install codecov

script:
  - python3 download_nltk_data.py
  - psql -c 'CREATE DATABASE travis_ci_test;' -U postgres
  - psql -c "CREATE USER admin WITH PASSWORD 'password';" -U postgres
  - psql -c "ALTER USER admin CREATEDB;" -U postgres
  
 after_success: codecov
  - python manage.py test
