branches:
  only:
    - master

language: python

python:
  - "3.6"

install:
  - pip install -r requirements.txt

script:
  - psql -c "CREATE USER admin WITH PASSWORD 'password';" -U postgres
  - python manage.py test