branches:
  only:
    - master

language: python

python:
  - "3.6"

before_install:
  - sudo apt install -y poppler-utils

addons:
  apt:
    update: true

install:
  - pip install -r requirements.txt

script:
  - psql -c "CREATE USER admin WITH PASSWORD 'password';" -U postgres
  - psql -c "ALTER USER admin CREATEDB;" -U postgres
  - python manage.py test