sudo: required

addons:
  apt:
    update: true
  chrome:
    stable

language: python

python:
  - "3.6"

before_install:
  - sudo apt install -y poppler-utils
  - sudo apt install python-pip
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &

install:
  - python -m pip install --upgrade pip
  - pip2 install pdfminer --user
  - pip install -r requirements.txt

script:
  - psql -c "CREATE USER admin WITH PASSWORD 'password';" -U postgres
  - psql -c "ALTER USER admin CREATEDB;" -U postgres
  - python manage.py test