#
# Module which stores AIML patterns and
# templates in .aiml format based on the outputs
# of the Keyword and Keyphrase extractors
#
# Author: Gabriel Ghiuzan
#


def aiml_generator(keywords, keyphrases):

	# An array which contains all the keywords generated by the Keyword extractor
	keywords = ["multiplexer"]

	# Stores an example of a keyphrase
	keyphrase = "A multiplexer is a special circuit that does this and that."

	# Initializes an array which will store AIML rules
	aiml_rules = []

	# Writes categories. A category is made up of a pattern and a template.
	# The keywords will be used for patterns. The keyphrases for templates
	for keyword in keywords:
		aiml_rules.append("\n        <pattern>WHAT IS * %s </pattern>" % keyword)
		aiml_rules.append("\n        <template> %s </template>" % keyphrase)

	return aiml_rules
